# netlify.toml

[build]
  # Lệnh để build trang React
  command = "npm run build"
  # Thư mục chứa kết quả build
  publish = "dist"
  # Thư mục chứa các Netlify Functions
  functions = "netlify/functions"

# Cấu hình chuyển hướng (rewrite) để API hoạt động
[[redirects]]
  # Bất kỳ yêu cầu nào đến /api/...
  from = "/api/*"
  # Sẽ được chuyển đến function 'api' với đường dẫn tương ứng
  to = "/.netlify/functions/api/:splat"
  # Status 200 có nghĩa là đây là một rewrite, không phải redirect 301/302
  status = 200